name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js version'
        required: false
        type: string
        default: '24'
      pnpm_version:
        description: 'PNPM version'
        required: false
        type: string
        default: '11.20.0'

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: ${{ inputs.pnpm_version || '11.20.0' }}

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node_version || '24' }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.minimumReleaseAge=0

      - name: Install Playwright browsers
        run: pnpm exec playwright install ffmpeg chromium firefox

      - parallel:
          - name: Typecheck
            run: .github/scripts/typecheck.sh

          - name: Unit test
            run: .github/scripts/unit-test.sh

          - name: End-to-end test
            run: .github/scripts/e2e-test.sh

          - name: Lint
            run: .github/scripts/lint.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [quality-gate]

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: ${{ inputs.pnpm_version || '11.20.0' }}

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node_version || '24' }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.minimumReleaseAge=0

      - name: Build
        run: bash .github/scripts/build.sh
